### ISSUE TITLE
npm install results in error (with node 11.10.1)

### ISSUE THREAD

**Issue by ropieur** [CorpGlory/grafana-plugin-template-webpack#14]
npm install command ends up with the following error:
```
In file included from ../../nan/nan.h:192:0,
                 from ../src/binding.cpp:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
               ^~~~~~~~
```

**Comment by jonyrock** [comment]
@ropieur we don't actively support this project. Please let us know ping@corpglory.com if you need support

**Comment by jonyrock** [comment]
please install node from there https://github.com/nodesource/distributions/blob/master/README.md

And, as the installer says, 

> You may also need development tools to build native addons:
> `sudo apt-get install gcc g++ make`

If you are not on Linux, you need to find a way to install native addons support on your machine:
https://nodejs.org/api/addons.html


@ropieur what OS do you use?

**Comment by jonyrock** [comment]
The reason for this problem was https://github.com/sass/node-sass which states following:

![image](https://user-images.githubusercontent.com/1022757/61183043-a6ec4600-a644-11e9-87f9-9c6345ae9f7a.png)

Now It works on Node 11+ after dependency update in package.json
